### ISSUE TITLE
Case statement is a tad slower than if/else

### ISSUE THREAD

**Issue by daino3** [girishso/pluck_to_hash#11]
I can submit a PR if you even care about this, but thought it might add to the performance argument in the README. 

see benchmark / detail here: http://www.daniellesucher.com/2013/07/ruby-case-versus-if/

OR TLDR:

``` ruby
n = 1 (last clause matches)
if:           7.4821e-07
threequal_if: 1.6830500000000001e-06
case:         3.9176999999999997e-07

n = 15 (first clause matches)
if:           3.7357000000000003e-07
threequal_if: 5.0263e-07
case:         4.3348e-07
```

**Comment by girishso** [comment]
Thanks @daino3 please feel free to go ahead.

Just make sure all the tests pass!
