### ISSUE TITLE
Returns column names as strings instead of symbols

### ISSUE THREAD

**Issue by katelovescode** [girishso/pluck_to_hash#13]
When I use this, I get back strings instead of symbols as the documentation shows.

```
Client.all.pluck_to_hash(:qbid,:name)
[{"qbid"=>"3", "name"=>"Client 1"}, {"qbid"=>"4", "name"=>"Client 2"}]
```

**Comment by katelovescode** [comment]
Upon further investigation - it looks like this returns a HashWithIndifferentAccess object.  In my use case I need to compare with a regular hash - exploring further how to do that, but this isn't an issue with the gem, closing my own Issue Report.

**Comment by girishso** [comment]
You may want to use http://api.rubyonrails.org/classes/ActiveSupport/HashWithIndifferentAccess.html#method-i-to_hash

**Comment by katelovescode** [comment]
That's great, I ended up using the alias `.to_h` and it worked. Thanks!
