### ISSUE TITLE
uninitialized constant PluckToHash::ActiveSupport (NameError)

### ISSUE THREAD

**Issue by Lemez** [girishso/pluck_to_hash#14]
Code:
@all_scores = DailyScore.all.pluck_to_hash(:date,:average).to_json.html_safe

On 'rackup' local serve command (am using Padrino), this is what I get:

/Users/JW/.rvm/gems/ruby-2.0.0-p353/gems/pluck_to_hash-0.2.0/lib/pluck_to_hash.rb:4:in `module:PluckToHash': uninitialized constant PluckToHash::ActiveSupport (NameError)

Added to Gemfile, bundled; tried to require it.

Any idea what to do?

**Comment by pironim** [comment]
@Lemez can you try explicit `require 'active_support'`

**Comment by Lemez** [comment]
Have required active_support in my controller as you suggest.

Same result: 

```
NoMethodError at /
undefined method `pluck_to_hash' for #<DailyScore::ActiveRecord_Relation:0x0000010b7575b8>
file: delegation.rb location: method_missing line: 136
```

**Comment by pironim** [comment]
hm. I think nobody test this gem against Padrino

**Comment by Lemez** [comment]
Padrino is basically Sinatra and Rack with a few helpers. I wonder, has it been tested with Sinatra? That should provide some answers. Thanks anyway.

**Comment by pironim** [comment]
I use it only with Rails (and before active_support merge).
Maybe you can downgrade and try previous version without active_support (only for HashWithIndifferentAccess)

**Comment by girishso** [comment]
Never thought somebody will use this with Sinatra!

It's using ActiveSupport::Concern since the start.  ActiveSupport is a dependency even for older versions right now.

**Comment by Lemez** [comment]
OK. Can you let me know what to downgrade / which version to try?

**Comment by girishso** [comment]
@Lemez just released version 0.1.4 that removes ActiveSupport dependency.

**Comment by Lemez** [comment]
Ok, will install and report back, thanks.

**Comment by Lemez** [comment]
Still same output:

```
>> $ rackup
/Users/JW/.rvm/gems/ruby-2.0.0-p353/gems/pluck_to_hash-0.1.4/lib/pluck_to_hash.rb:29:in `<top (required)>': uninitialized constant ActiveRecord (NameError)
```

**Comment by girishso** [comment]
Try requiring ActiveRecord first. Then this gem

**Comment by Lemez** [comment]
Fixed!

 I required active_record as you suggested, and it didn't work, then moved the position of the gems in my Gemfile. 

So whereas previously I had:

```
gem 'pluck_to_hash', '~> 0.1.4'
gem 'activerecord', '>= 3.1', :require => 'active_record'
```

Now this fixed it:

```
gem 'activerecord', '>= 3.1', :require => 'active_record'
gem 'pluck_to_hash', '~> 0.1.4'
```

I didn't realise the position of gems in the Gemfile could be so important.
Thanks guys.
