### ISSUE TITLE
Incorret hash returned when using joins and declarative columns

### ISSUE THREAD

**Issue by MrHubble** [girishso/pluck_to_hash#19]
`pluck` can be used across multiple tables and:

> While not absolutely necessary, the pluck query across multiple tables would be more safely written as pluck("users.first_name, users.last_name, roles.title") to correctly scope columns to their respective table.
> http://collectiveidea.com/blog/archives/2015/05/29/how-to-pluck-like-a-rails-pro/

When I run something like `pluck_to_hash("users.first_name, users.last_name, roles.title")`

I get results similar to:

```
{"users.first_name, users.last_name, roles.title"=>["john","smith", "accountant"]} 
```

**Comment by rasmar** [comment]
just use pluck_to_hash("users.first_name as user_first_name", "users.last_name as user_last_name", "roles.title as role_title")
