### ISSUE TITLE
1.0.1 regression/bug

### ISSUE THREAD

**Issue by naerymdan** [girishso/pluck_to_hash#25]
If you run a pluck_to_hash using 2 aliased operations, the result becomes weird/shifted.

Prices.pluck_to_hash('coalesce(sum(high_price - low_price), 0) as difference', 'count(prices.id) as prices_count')

gives 
{
  "coalesce(sum(high_price - low_price), 0)"=>#<BigDecimal:b066868,'0.2E2',9(18)>,
  "amount"=>1,
  "prices_count"=>nil
}

**Comment by wct** [comment]
I have the same issue on coalesce with 1.0.1
Works after revert to 1.0.0

**Comment by girishso** [comment]
v1.0.2 fixes this regression. 

Thanks for reporting!

**Comment by wct** [comment]
Thanks! Solved the issue.
